### ISSUE TITLE
Inline editor bug with 'visible on web' dropdown text positioning

### ISSUE THREAD

**Issue by matt-quoin** [WarpWorks/warpjs#234]
Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)

![image002](https://user-images.githubusercontent.com/8090999/58026379-580eae00-7ae4-11e9-9b7f-c05b8023f7ab.jpg)

**Comment by quoininc-huudatran** [comment]
Doesn't seem to consistently happening. It may be related to CSS not fully loaded. This happened multiple times with VPN. Clearing cache and reloading page seems to fix the issue.
