### ISSUE TITLE
PDF Generator: Cover image functionality

### ISSUE THREAD

**Issue by matt-quoin** [WarpWorks/warpjs#282]
- Create a migration script to add "PDF Cover Image" to the image type enumeration;
- Create "Images" panel in the `DefaultPageView` if not present, and add the relationship `Images` for entities that are inheriting from `Content`;
- Create logic in generate PDF to take images in a priority order:
    - PDF Cover Image (type=`PdfCoverImage`) if it exists;
    - First image of first paragraph in `Overview` if it exists; or
    - Default image.

**Comment by quoininc-huudatran** [comment]
Back-end work done in a8bcf7a, so unassigned myself from issue. Waiting for migration script to move card to be tested.

**Comment by quoininc-huudatran** [comment]
The image type `PdfCoverImage` has been manually added to PROD to simplify the migration script.

**Comment by quoininc-huudatran** [comment]
In prod with `prod-20190909`.
